### ISSUE TITLE
Error "You are missing configkeys in your config.yaml-file. Add these before restarting the bot."

### ISSUE THREAD

**Issue by heisenberg2980** [Waterboy1602/Addarr#152]
Addarr has starting failing and sending this error to telegram after the last update:

```
You are missing the following configkeys in your config.yaml-file: 'sonarr/narrowRootFolderNames', 'sonarr/addRequesterIdTag', 'radarr/narrowRootFolderNames', 'radarr/addRequesterIdTag', 'adminNotifyId'. 
Add these before restarting the bot.
```

As I have "restart: unless-stopped" in my config the messages were being sent in a loop until I stopped the container and added the missing parameters.

Adding the missing parameters solved the issue, I am just creating this issue so other people having the same problem are aware of the solution, but my question is why are these parameters now mandatory? can these (and any other future new parameter added to the settings) be set as optional to avoid breaking changes? and why has this started happening just now if the last release of this package was done on October 2023?

I went to dockerhub (https://hub.docker.com/r/waterboy1602/addarr) and I realised the package has been updated couple of days ago, how can the package be updated in dockerhub if there is no new tag/release in github?

**Comment by gioxx** [comment]
Same here.

**Comment by baconsashimi** [comment]
@heisenberg2980 can you post an example of your config.yaml so we can see how you added those additional parameters? I am unclear on how to get things working again. Appreciate your help!

**Comment by gioxx** [comment]
> @heisenberg2980 can you post an example of your config.yaml so we can see how you added those additional parameters? I am unclear on how to get things working again. Appreciate your help!

https://github.com/Waterboy1602/Addarr/blob/master/config_example.yaml

For example: https://github.com/Waterboy1602/Addarr/blob/master/config_example.yaml#L17

**Comment by Waterboy1602** [comment]
I'm sorry for the experienced troubles. I didn't realise having `restart: unless-stopped` in their config, would make the bot resending the messages endlessly.

> Adding the missing parameters solved the issue, I am just creating this issue so other people having the same problem are aware of the solution, but my question is why are these parameters now mandatory? can these (and any other future new parameter added to the settings) be set as optional to avoid breaking changes? and why has this started happening just now if the last release of this package was done on October 2023?

I've chosen to make all settings mandatory. Just to prevent that some future update totally breaks the bot for some people. To prevent the loop of messages, i'll look into changing the feature so that the bot only sends one message even if the bot keeps restarting.

> I went to dockerhub (https://hub.docker.com/r/waterboy1602/addarr) and I realised the package has been updated couple of days ago, how can the package be updated in dockerhub if there is no new tag/release in github?

This repo is configured to make a new Docker image with the push of every commit and not just with tags/releases. This because I don't really keep track of tags/releases and often forget to make new ones. 
If you propose some way to make releasing new tags/releases less time consuming, I'll take a look into it.

**Comment by heisenberg2980** [comment]
@Waterboy1602 thanks for the clarification, my question was more about the package being updated in dockerhub without those changes being reflected in github. It seems that you have made the changes locally in your machine and not merged those changes to the github repo, which means github doesn´t contain the latest version of the code, so any pull request in github would be done against an old version of the code and not the latest, is my understanding correct?
And regarding the tags/release, I am not sure what IDE you use, but for instance using Visual Studio Code with the "github pull request" extension you can create tags/releases automatically every time you commit the code to the repo

**Comment by Waterboy1602** [comment]
@heisenberg2980 

I've just checked and the changes are visible in the Github Repo. The commit that caused this hassle, was [ea23084](https://github.com/Waterboy1602/Addarr/commit/ea2308449180cd3433379f5d42b6ae187e8c03d3). Because of the fact that I'm the maintainer of this repo, I commit directly to the main branch without PR.

You're suggestion about making tags/releases with VS Code is a good one. I'll look into doing this in the future.

**Comment by heisenberg2980** [comment]
@Waterboy1602 you are completely right, please ignore my last comment as I must have completely missed that commit
