### ISSUE TITLE
Bot to send notification once download is completed

### ISSUE THREAD

**Issue by OrionTheWaffle** [Waterboy1602/Addarr#17]
It would just be a simple notification that tells the user that the item they requested for has completed downloading. That's it. 

Thanks and really appreciate the work that you've put in here, changed my workflow!

**Comment by toddrob99** [comment]
This would require a database to store info about who added a movie/series, and then Addarr would need to actively monitor sonarr/radarr to identify when that item has been downloaded and send a message to the person who requested it. Not terribly complex, but also not trivial to add. 

Would you expect the bot to notify the requester for each added episode of a series they requested? This seems like it might not be that useful, because others may also be interested in those updates and only one person can be considered the requester for the entire series (same goes for a movie). It might be better to have a Telegram group with all interested parties where sonarr and radarr post when all items are added (which is currently supported by both sonarr and radarr).

**Comment by nastye** [comment]
Suggested solution: add tag to user on auth, add that tag to show/movie on add and set up sonarr/radarr telegram connection based on those tags
