### ISSUE TITLE
Using reactions than the keyboard for selection

### ISSUE THREAD

**Issue by OrionTheWaffle** [Waterboy1602/Addarr#18]
I've noticed that when you put the bot in a group and when somebody tries to request something, everyone's affected with the bot changing their keyboard for choices.

Once the request has been made by the user, I've also realised that the other users will have the last "reply" of the movie on top of their keyboard. That's kinda strange.

Plus, I feel like if we use reactions than the keyboard selection, it'll be more stable and less visible queries on the chat.

Here's a screenshot of what I meant by using reactions for selections.
So that the input is a button rather than a wordy response from the user. 

<img width="306" alt="Screenshot 2020-06-11 at 6 36 35 PM" src="https://user-images.githubusercontent.com/44424766/84376076-12eb7b80-ac13-11ea-959d-e4e8cded0ab5.png">

Hope this is possible and thanks again!

**Comment by Waterboy1602** [comment]
That's indeed something that I looked into. At the beginning I also wanted to do it that way. I have to be honest I didn't had quite an idea what I was doing. So I went then with my other solution: keyboard selection. Just because it was easier to program.

I also have the same idea that reactions would be simpler. But before that I can do this, I need to look a lot deeper into this. I will see what I can do.

Thank you for all your suggestion!
