### ISSUE TITLE
Transmission inside Docker : Transmission-remote: not found

### ISSUE THREAD

**Issue by phileastv** [Waterboy1602/Addarr#40]
Hello here ! 👋 

I'm very interested by this project ! But I have troubles to make the Transmission feature works.

Even if I have correctly set my params inside `config.yaml`, every time I ask the bot to change the transmission speed I get this error message in the console `sh: transmission-remote: not found`, _(I already have the `debug-log` option activated in my config file)_.

I understood by reading [this bit of code](https://github.com/Waterboy1602/Addarr/blob/97c44307716216e6932f02ca44fb66dbafa92be1/addarr.py#L217) that Addarr uses the `transmission-remote` CLI and composes the corresponding command with `os.system`. But does Addarr uses the CLI inside of Addar's own docker container, or execute the command on the host ?

For my case, Transmission is itself located inside a docker container, so `transmission-remote` is not in the PATH of my host system. But that command works correctly if I execute the command inside my docker container like this`docker container exec transmission transmission-remote localhost --auth transmission:mypassword --no-alt-speed`.

If this feature is not supported when Transmission is itself in a docker container, maybe I can see if I can make a PR change this in the config file _(and execute the command with docker exec itself)_.

**Comment by Waterboy1602** [comment]
I've indeed developed this feature when I wasn't using docker containers myself. I had back then an Iocage jail where Transmission and Addarr were running on the same instance. Back then with the Iocage jail it was possible to just perform an `os.system` command to let it work.  

I'm now also using Docker containers, but didn't yet enabled the Transmission feature. It's indeed more logical to have both Addarr and Transmission running in a different container and I get where the problem is coming from. So feel free to make a PR, I'm always open to new features.
