### ISSUE TITLE
trying to install on rpi4

### ISSUE THREAD

**Issue by olegosipenko87** [Waterboy1602/Addarr#55]
Hello
Trying to install on rpi4 (Raspbian): 
1. apt-get install libxml2-dev libxslt1-dev python3-libxml2 python3-lxml unrar-free
2. git clone https://github.com/Waterboy1602/Addarr.git
3. pip install -r requirements.txt
And when _python addarr.py_ then I get this :

```
root@raspberrypi:/usr/Addarr# python addarr.py
  File "addarr.py", line 32
    logger.debug(f"Addarr v{__version__} starting up...")
                                                       ^
SyntaxError: invalid syntax
```

**Comment by jtrosper** [comment]
Try invoking it with: python3 addarr.py From: olegosipenko87 <notifications@github.com>Date: Monday, March 1, 2021 at 1:54 PMTo: Waterboy1602/Addarr <Addarr@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [Waterboy1602/Addarr] trying to install on rpi4 (#55)HelloTrying to install on rpi4 (Raspbian):apt-get install libxml2-dev libxslt1-dev python3-libxml2 python3-lxml unrar-freegit clone https://github.com/Waterboy1602/Addarr.gitpip install -r requirements.txtAnd when python addarr.py then I get this :root@raspberrypi:/usr/Addarr# python addarr.py  File "addarr.py", line 32    logger.debug(f"Addarr v{__version__} starting up...")                                                       ^SyntaxError: invalid syntax—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by skynet01** [comment]
I am getting the same issue on my rpi3

**Comment by olegosipenko87** [comment]
> try starting it with python3 addarr.py

thank
It worked

**Comment by skynet01** [comment]
Awesome! this should be added to the install guide. Especially since pip didn't work for me either and I had to use pip3.

**Comment by Waterboy1602** [comment]
I've added it to the [Linux wiki](https://github.com/Waterboy1602/Addarr/wiki/Installation-on-Linux), so in the future you can find these suggestions there.
