### ISSUE TITLE
No entries shown after "Please select a path for the movie or series"

### ISSUE THREAD

**Issue by n0vae** [Waterboy1602/Addarr#60]
Hello,

**First of all, thank you for your dev ! Great job here.**

I'm having an issues with Sonarr request when submitting new serie to be added to my Telegram bot. 
Everything's fine until the "select path" part. Just after receiving message "Please select a path for the movie or series", no entries are shown and when trying to write the path, nothing happend. 

No problem with Radarr part as I left only one path for movies directory so for movies, it doesn't ask me this.

To be noted that it worked until I changed Sonarr volumes mounted/linked in my Docker config. I had to reconfigure manually tv shows path in Sonarr but now it's all good again, except that Addarr is not able to see my TVSHOW directory anymore.

Any idea on this ? Nothing special shown or related in terminal/logs.

Thank you in advance.

**Comment by Waterboy1602** [comment]
Thank you for the compliment and my apology for this late answer!

You're the first to report this bug, so I don't know if it's something at your side or with Addarr. I'll try to look into this in the next couple of days. I'll see if I find something.

I want to say though that I'm not that used with using the path function in Addarr. I've never used it before. Please report back to me if by any chance this bug is already fixed.

**Comment by n0vae** [comment]
Hey, thank you for your answer. 
I guess I can find a workaround with only one library and so bypass this prompt. Furthermore I will install a new Sonarr instance in order to correct other minor bugs. No need to spend more time on this (for me at least). 

Thank you and please keep updating this great code.
Warm greetings

**Comment by Biscotte31** [comment]
Hi, I have exactly the same symptoms, but when looking for a movie (using Radarr then). What is the workaround to avois this "choose a path" message ?

**Comment by n0vae** [comment]
Hello Biscotte,
The use of only one directory, avoiding the prompt of choosing one.

Cheers
